version: '3.8'

services:
  backend:
    build: ./backend
    container_name: portfolio-backend
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/portfolio   # adjust if you're using Atlas
    expose:
      - "5000"

  frontend:
    build: ./frontend
    container_name: portfolio-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: portfolio-mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:latest
    container_name: portfolio-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  mongo-data:

